/*
 * @Author: 王利
 * @Date: 2020-12-01 15:15:44
 * @LastEditors: 王利
 * @LastEditTime: 2020-12-04 12:46:52
 */
export const LOGININFO = "LOGININFO";
export const LOGOUT = "LOGOUT";
export const SIZE = "SIZE";
export const THEME_COLOR = "THEME_COLOR";
export const ADD_ERROR_LOG = "ADD_ERROR_LOG";
export const CLEAR_ERROR_LOG = "CLEAR_ERROR_LOG";
export const TOGGLE_SIDEBAR = "TOGGLE_SIDEBAR";
export const CLOSE_SIDEBAR = "CLOSE_SIDEBAR";

export const ADD_VISITED_VIEW = "ADD_VISITED_VIEW";
export const ADD_CACHED_VIEW = "ADD_CACHED_VIEW";
export const DEL_VISITED_VIEW = "DEL_VISITED_VIEW";
export const DEL_CACHED_VIEW = "DEL_CACHED_VIEW";
export const DEL_OTHERS_VISITED_VIEWS = "DEL_OTHERS_VISITED_VIEWS";
export const DEL_OTHERS_CACHED_VIEWS = "DEL_OTHERS_CACHED_VIEWS";
export const DEL_RIGHT_VISITED_VIEWS = "DEL_RIGHT_VISITED_VIEWS";
export const DEL_RIGHT_CACHED_VIEWS = "DEL_RIGHT_CACHED_VIEWS";
export const DEL_LEFT_VISITED_VIEWS = "DEL_LEFT_VISITED_VIEWS";
export const DEL_LEFT_CACHED_VIEWS = "DEL_LEFT_CACHED_VIEWS";
export const DEL_ALL_VISITED_VIEWS = "DEL_ALL_VISITED_VIEWS";
export const DEL_ALL_CACHED_VIEWS = "DEL_ALL_CACHED_VIEWS";
export const CREAT_VISITED_VIEW = "CREAT_VISITED_VIEW";
